### PR TITLE
Fix missing quotation mark

### PR DESCRIPTION
**Pull request by lucastanure**

### CODE REVIEW

**Comment by mradulan** [comment]
@elstryan can you answer this?

**Comment by mradulan** [comment]
@lucastanure, Thank you for pointing it out. But can you provide us as to where it is causing an error for you?

**Comment by lucastanure** [comment]
When using automated_install.sh for an embedded debian linux. Not raspberry pi3. 
I do a few modifications to use on my system, but this one is a bug for me,

**Comment by dhpp** [comment]
Hi lucastanure - sorry this thread has not been updated for a while.  We've taken a note of the issue and the fix you suggest, and will hope to deploy a formal update in the near future.  Thanks for bringing this to our attention.

**Comment by javadev** [comment]
+

**Pull request closed without merging**
