### PR TITLE
Add A Physical Button

### PR DESCRIPTION
**Pull request by Eddie-Hartman**
This is the way that I was able to add a button to the existing code. It is far from perfect, but it works. I also added the dependencies and a couple of other changes so that users wouldn't have to.

### CODE REVIEW

**Comment by artcriticism** [comment]
> [http://artcriticism.github.io/ISIS](url)

**Comment by Eddie-Hartman** [comment]
Excuse my ignorance, but is there something that I need to do here? I understand that the code is by no means clean. It was just a quick and dirty solution. If I find time I may be able to clean it up. Is that what you are waiting for?

**Comment by moviemanic** [comment]
I was able to get the plain Alexa Pi up and running, but after following your instructions not only did the button not work, but the regular alexa didn't work anymore either. Do you have any idea what would've caused that?

**Comment by Eddie-Hartman** [comment]
Did you stop the service before making the changes? Could you post a log of errors? Which pi are you using? I've done this on the pi 3 and b+, but any should work. There's also the go to, try restarting.

**Comment by moviemanic** [comment]
I got the Alexa service working with the gui button! Do you know if there's any way to have a pull down logic in the pi4j documentation? I tried changing "PinPullResistance.PULL_DOWN);" to "PULL_UP" but that doesn't seem to work. All of the other buttons on my board are routed from ground to a specific pin and I'd like to wire this one the same way if possible.

**Comment by Eddie-Hartman** [comment]
I don't think that it would matter since the listener is just looking for a change, but I don't really know. I would think that as long as you wire for pull up or down properly than it will work. I don't know that much about it to help more though. [This](http://pi4j.com/example/listener.html) is the example that I used so if you want to do some research then that would be the best place to start.

**Comment by moviemanic** [comment]
when I paste in the specific code changes into the code everything works, however when I download and use the files you provide I get this error:
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project sample-java-client: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by dskidmor** [comment]
Thanks for the pull request! At this time, we are only considering pull requests that are bug fixes. This is a great idea though! Keep tinkering with it on your own fork and let us know how it goes.

**Pull request closed without merging**
