### PR TITLE
updated POM.xml

### PR DESCRIPTION
**Pull request by balaraju1278**
More developers getting error on building here i am updating pom.xml file it working properly without any changes

### CODE REVIEW

**Comment by mradulan** [comment]
Thank you for the pull request. Our process is to make changes internally and run all test before pushing the change to github in the form of a new release. I have added this to our internal tracking system to be assessed and prioritized.

**Comment by mradulan** [comment]
Hi @balaraju1278 , can you specify what issues are getting resolved by this change?

**Comment by balaraju1278** [comment]
Hi Mradulan , Many Developers are facing issues in when running java-client (maven building) with mvn exec:exec i just modified with mvn exec:java with some modifications in pom.xml it will resolve mojoExecutionExceptions

**Comment by mradulan** [comment]
Hi @balaraju1278 , our future releases will resolve this issue. Thank you!

**Pull request closed without merging**
